version: '3.8'

services:
  db:
    image: postgres:16.1
    container_name: node-next-ql-app-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: node:21.5.0-alpine3.18
    container_name: node-next-ql-app-backend
    restart: always
    working_dir: /app
    command: sh -c "npm install -g pnpm && pnpm install --frozen-lockfile && pnpm run start"
    environment:
      NODE_ENV: development
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data:
